### ISSUE TITLE
6+显示问题

### ISSUE THREAD

**Issue by LargeShrimp** [interchen/ImagePlayerView#10]
首页是图片会有问题，一张图片不能铺满屏幕，然后是pageControl 不会跟着滚动，

**Comment by interchen** [comment]
@LargeShrimp 可以参考一下我的Sample，如果还有问题的话，麻烦把你的示例工程发我邮件inter.chen@gmail.com，我确认一下看看。
因为我在自己的项目都使用着，至今还没有遇到你说的问题。

**Comment by LargeShrimp** [comment]
Demo 正常，但是demo的方法  [self.imagePlayerView initWithCount:self.imageURLs.count delegate:self];也已经弃用了。

**Comment by interchen** [comment]
demo早已经没有init方法了，请使用delegate去实现，或是参看最新的demo
