### ISSUE TITLE
滚动到最后一张图片，stop timer，再次打开timer，不会再滚动

### ISSUE THREAD

**Issue by bioshrek** [interchen/ImagePlayerView#15]
如题
原因应该是reloadData的实现有BUG。reloadData时，将currentPage置为0时，没有将scrollView的contentOffset也置为0，导致2者没有同步。

将如下代码
`- (void)reloadData
{
    self.pageControl.currentPage = 0;
}`
改为
`- (void)reloadData
{
    self.pageControl.currentPage = 0;
    self.scrollView.contentOffset = CGPointZero;
}`

或者用别的办法将currentPage和contentOffset同步起来即可。

**Comment by interchen** [comment]
@bioshrek 核心代码已经重构，不会再有这个问题，你可以更新版本到2.0.0试一下
