### ISSUE TITLE
当系统设置粗字体显示时，初次启动，轮播图不会转动

### ISSUE THREAD

**Issue by FAppleG** [interchen/ImagePlayerView#16]
经检查是你的位置判断有问题line:306
修改为：if (self.imagePlayerViewDelegate && [self.imagePlayerViewDelegate respondsToSelector:@selector(imagePlayerView:didScorllIndex:)]) {
就ok了

**Comment by interchen** [comment]
@FAppleG 你使用的是1.x版本还是2.0.0？貌似行号对不上，而且你发的这段代码与我源码是一样的？没看出区别来？

**Comment by FAppleG** [comment]
是1.1.2版本，2.0版本的轮播有问题，我还没有细看
发自 网易邮箱大师
在2016年05月24日 15:25，Chen Yanjun 写道:

@FAppleG 你使用的是1.x版本还是2.0.0？貌似行号对不上，而且你发的这段代码与我源码是一样的？没看出区别来？

**Comment by interchen** [comment]
@FAppleG 你说的2.0轮播有问题能否说仔细一些？

**Comment by interchen** [comment]
@FAppleG 1.x版本已经不打算维护了哦，有严重的性能问题

**Comment by FAppleG** [comment]
@interchen  我昨天试的 当轮播到最后一张图的时候，反向回到第一张图再次轮播，不是顺序轮播
