### ISSUE TITLE
Put ImagePlayerView in a tableView will prevent scrollToTop.

### ISSUE THREAD

**Issue by kilik52** [interchen/ImagePlayerView#3]
You can add 

````
    self.scrollView.scrollsToTop = NO;
```` 

in ImagePlayerView.m, line 75 to fix that problem.

**Comment by BaiCanLin** [comment]
嗨，这个开源写的非常好，但是在 ios6下效果不太好 ，不支持手动无限滚动哦～

**Comment by interchen** [comment]
说句实在话，写的时候没有想好怎么去实现无限滚动，最近也没有在打理了。iOS6基本没有测过，如果你需要支持iOS6的话，可以搜索其它库看看

**Comment by BaiCanLin** [comment]
目前没有找到比你这个更好用的了，如果添加无限滚动上去，效果几乎美美的

**Comment by interchen** [comment]
@kilik52 Done! Thanks.
