### ISSUE TITLE
iOS 6中与UITableViewCell重用机制的使用问题

### ISSUE THREAD

**Issue by hi-guy** [interchen/ImagePlayerView#7]
在iOS 6的情况下，组件是放入UITableViewCell里面。 滑动的时候，下一张图片即将显示完全，这一过程中，讲添加了ImagePlayerView的Cell滚出屏幕外，然后再滑回到屏幕内，这个时候添加到组件里面的ImageView的origin.x都会往左偏移。不管是否开启了自动滚动。

**Comment by interchen** [comment]
你好
imageView.clipsToBounds = YES;
这样设置可以暂时解决这个问题

**Comment by hi-guy** [comment]
你好 我纠正一下 情况是在CollectionViewCell里面造成

**Comment by interchen** [comment]
你好，我还没有在UICollectionViewCell中测试过，这两天抽空再看一下，最近有点忙
建议你把view放在UICollectionView的Header
