### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by AndyLeeBlue** [interchen/ImagePlayerView#9]
当push到另一个view，再返回后，图片会只显示一半，当自动滚动时才恢复正常。

**Comment by fanly** [comment]
如何在swift使用呢 谢谢

**Comment by interchen** [comment]
@AndyLeeBlue 没有复现出你的问题，如果方便的话，把你的示例工程发给我看一下

**Comment by interchen** [comment]
@fanly Swift是兼容OC的，你去查阅一下相关的资料吧

**Comment by AndyLeeBlue** [comment]
我是用在storyboard里面的，uiviewcontroller用自适应尺寸的方式，问题估计在这里
